[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"
  NETLIFY_SITE_NAME = "www.verifiedandreviewed.com"

# Cache optimization
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA redirect for React Router - MUST be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Scheduled Functions Configuration
[functions]
  # Functions directory is already defined under [build]
  
  # Schedule the refresh-offerings function to run daily at 2 AM UTC
  [[functions.scheduled]]
    name = "refresh-offerings"
    cron = "0 2 * * *"
